language: node_js
node_js:
  - "13.8"
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_cdc0677920ab_key -iv $encrypted_cdc0677920ab_iv
    -in secrets.tar.gz.enc -out secrets.tar.gz -d
  - tar xf secrets.tar.gz
script:
  - npm install
  - npm run build
  - docker run -it --mount type=bind,source="$(pwd)",target=/source google/cloud-sdk bash -c
     "cd /source && gcloud auth activate-service-account --key-file=key.json && gsutil rsync -R build/ gs://poc.timereport.codelabs.se/"
